/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Alert = IDL.Record({
  'direction' : IDL.Text,
  'active' : IDL.Bool,
  'targetPrice' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Holding = IDL.Record({
  'name' : IDL.Text,
  'buyPrice' : IDL.Float64,
  'amount' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Coin = IDL.Record({
  'change24h' : IDL.Float64,
  'circulatingSupply' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'volume24h' : IDL.Float64,
  'change7d' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'time' : IDL.Int,
  'volume' : IDL.Float64,
});
export const Signal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : IDL.Int,
  'symbol' : IDL.Text,
  'signalType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAlert' : IDL.Func([Alert], [], []),
  'addHolding' : IDL.Func([Holding], [], []),
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSignal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteSignal' : IDL.Func([IDL.Nat], [], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllCoins' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandleData' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Candle)],
      ['query'],
    ),
  'getCoin' : IDL.Func([IDL.Text], [Coin], ['query']),
  'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
  'getMarketSentiment' : IDL.Func([], [IDL.Float64], ['query']),
  'getSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getTopGainers' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
  'getTopLosers' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAlert' : IDL.Func([IDL.Text], [], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'removeHolding' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleAlert' : IDL.Func([IDL.Text], [], []),
  'updateHolding' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Alert = IDL.Record({
    'direction' : IDL.Text,
    'active' : IDL.Bool,
    'targetPrice' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Holding = IDL.Record({
    'name' : IDL.Text,
    'buyPrice' : IDL.Float64,
    'amount' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Coin = IDL.Record({
    'change24h' : IDL.Float64,
    'circulatingSupply' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'volume24h' : IDL.Float64,
    'change7d' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'time' : IDL.Int,
    'volume' : IDL.Float64,
  });
  const Signal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : IDL.Int,
    'symbol' : IDL.Text,
    'signalType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAlert' : IDL.Func([Alert], [], []),
    'addHolding' : IDL.Func([Holding], [], []),
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSignal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteSignal' : IDL.Func([IDL.Nat], [], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllCoins' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandleData' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Candle)],
        ['query'],
      ),
    'getCoin' : IDL.Func([IDL.Text], [Coin], ['query']),
    'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
    'getMarketSentiment' : IDL.Func([], [IDL.Float64], ['query']),
    'getSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getTopGainers' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
    'getTopLosers' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAlert' : IDL.Func([IDL.Text], [], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'removeHolding' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleAlert' : IDL.Func([IDL.Text], [], []),
    'updateHolding' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };