/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'direction' : string,
  'active' : boolean,
  'targetPrice' : number,
  'symbol' : string,
}
export interface Candle {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'time' : bigint,
  'volume' : number,
}
export interface Coin {
  'change24h' : number,
  'circulatingSupply' : number,
  'marketCap' : number,
  'name' : string,
  'rank' : bigint,
  'volume24h' : number,
  'change7d' : number,
  'price' : number,
  'symbol' : string,
}
export interface Holding {
  'name' : string,
  'buyPrice' : number,
  'amount' : number,
  'symbol' : string,
}
export interface Signal {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'timestamp' : bigint,
  'symbol' : string,
  'signalType' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAlert' : ActorMethod<[Alert], undefined>,
  'addHolding' : ActorMethod<[Holding], undefined>,
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSignal' : ActorMethod<[string, string, string, string], undefined>,
  'deleteSignal' : ActorMethod<[bigint], undefined>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllCoins' : ActorMethod<[], Array<Coin>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandleData' : ActorMethod<[string, string], Array<Candle>>,
  'getCoin' : ActorMethod<[string], Coin>,
  'getHoldings' : ActorMethod<[], Array<Holding>>,
  'getMarketSentiment' : ActorMethod<[], number>,
  'getSignals' : ActorMethod<[], Array<Signal>>,
  'getTopGainers' : ActorMethod<[], Array<Coin>>,
  'getTopLosers' : ActorMethod<[], Array<Coin>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchlist' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAlert' : ActorMethod<[string], undefined>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'removeHolding' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleAlert' : ActorMethod<[string], undefined>,
  'updateHolding' : ActorMethod<[string, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];